mvc_blog_projesi/Controllers/AboutController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc_blog_projesi.Controllers
{
    [AllowAnonymous]

    public class AboutController : Controller
    {
        // GET: About
        AboutManager abm = new AboutManager(new EfAboutDal());

        public ActionResult Index()
        {
            var aboutcontent = abm.GetList();
            return View(aboutcontent);
        }

        public PartialViewResult Footer()
        {
           var aboutcontentlist= abm.GetList();
            return PartialView(aboutcontentlist);
        }

        public PartialViewResult MeetTheTeam()
        {
            AuthorManager autman=new AuthorManager(new EfAuthorDal());
            var authorlist= autman.GetList();
            return PartialView(authorlist);
        }

        [HttpGet]
        public ActionResult UpdateAboutList()
        {
            var aboutlist=abm.GetList();
            return View(aboutlist);
        }

        [HttpPost]
        public ActionResult UpdateAbout(About p)
        {
            abm.TUpdate(p);
                return RedirectToAction("UpdateAboutList");
        }


    }
}

mvc_blog_projesi/Controllers/AuthorController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc_blog_projesi.Controllers
{
    public class AuthorController : Controller
    {
        // GET: Author
        BlogManager blogmanage=new BlogManager(new EfBlogDal());
        AuthorManager authormanager=new AuthorManager(new EfAuthorDal());

        [AllowAnonymous]

        public PartialViewResult AuthorAbout(int id)
        {
            var authordetail=blogmanage.GetBlogByID(id);
            return PartialView(authordetail);
        }

        [AllowAnonymous]

        public PartialViewResult AuthorPopularPost(int id)
        {
            var blogauthorid = blogmanage.GetList().Where(x => x.BlogID == id).Select(y => y.AuthorID).FirstOrDefault();

            var authorblogs = blogmanage.GetBlogByAuthor(blogauthorid);
            return PartialView(authorblogs);
        }

        public ActionResult AuthorList()
        {
            var authorlists = authormanager.GetList();
            return View(authorlists);
        }

        [HttpGet]
        public ActionResult AddAuthor()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAuthor(Author p)
        {
            AuthorValidator authorValidator = new AuthorValidator();
            ValidationResult results = authorValidator.Validate(p);
            if (results.IsValid)
            {
                authormanager.AuthorAdd(p);
                return RedirectToAction("AuthorList");
            }

            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }

        [HttpGet]
        public ActionResult AuthorEdit(int id)
        {
            Author author = authormanager.GetByID(id);

            return View(author);
        }

        [HttpPost]
        public ActionResult AuthorEdit(Author p)
        {
            AuthorValidator authorValidator = new AuthorValidator();
            ValidationResult results = authorValidator.Validate(p);
            if (results.IsValid)
            {
                authormanager.TUpdate(p);
                return RedirectToAction("AuthorList");
            }
            
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();

        }
    }
}

mvc_blog_projesi/Controllers/BlogController.cs
using BusinessLayer.Concrete;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using EntityLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;

namespace mvc_blog_projesi.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog

        BlogManager bm = new BlogManager(new EfBlogDal());

        CommentManager cm = new CommentManager(new EfCommentDal());

        [AllowAnonymous]
        public ActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        public PartialViewResult BlogList(int page=1)
        {
            var bloglist = bm.GetList().ToPagedList(page,6);

            return PartialView(bloglist);
        }

        [AllowAnonymous]
        public PartialViewResult FeaturedPost()
        {
            //1. Post
            var posttitle1 = bm.GetList().OrderByDescending(z=>z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogName).FirstOrDefault();
            var postimage1= bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate1= bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogDate).FirstOrDefault();
            var blogid1 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 1).Select(y => y.BlogID).FirstOrDefault();

            ViewBag.posttitle1=posttitle1;
            ViewBag.postimage1=postimage1;
            ViewBag.blogdate1=blogdate1;
            ViewBag.blogid1 = blogid1;


            //2. Post
            var posttitle2 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogName).FirstOrDefault();
            var postimage2 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate2 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogDate).FirstOrDefault();
            var blogid2 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 2).Select(y => y.BlogID).FirstOrDefault();

            ViewBag.posttitle2 = posttitle2;
            ViewBag.postimage2 = postimage2;
            ViewBag.blogdate2 = blogdate2;
            ViewBag.blogid2 = blogid2;

            //3. Post
            var posttitle3 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogName).FirstOrDefault();
            var postimage3 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate3 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogDate).FirstOrDefault();
            var blogid3 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 3).Select(y => y.BlogID).FirstOrDefault();

            ViewBag.posttitle3 = posttitle3;
            ViewBag.postimage3 = postimage3;
            ViewBag.blogdate3 = blogdate3;
            ViewBag.blogid3 = blogid3;

            //4. Post
            var posttitle4 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogName).FirstOrDefault();
            var postimage4 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate4 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogDate).FirstOrDefault();
            var blogid4 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 4).Select(y => y.BlogID).FirstOrDefault();

            ViewBag.posttitle4 = posttitle4;
            ViewBag.postimage4 = postimage4;
            ViewBag.blogdate4 = blogdate4;
            ViewBag.blogid4 = blogid4;

            //5. Post
            var posttitle5 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 5).Select(y => y.BlogName).FirstOrDefault();
            var postimage5 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 5).Select(y => y.BlogImage).FirstOrDefault();
            var blogdate5 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 5).Select(y => y.BlogDate).FirstOrDefault();
            var blogid5 = bm.GetList().OrderByDescending(z => z.BlogID).Where(x => x.CategoryID == 5).Select(y => y.BlogID).FirstOrDefault();

            ViewBag.posttitle5 = posttitle5;
            ViewBag.postimage5 = postimage5;
            ViewBag.blogdate5 = blogdate5;
            ViewBag.blogid5 = blogid5;

            return PartialView();
        }

        [AllowAnonymous]
        public PartialViewResult OtherFeaturedPost()
        {
            return PartialView();
        }

        [AllowAnonymous]
        public ActionResult BlogDetails()
        {
            return View();
        }

        [AllowAnonymous]
        public PartialViewResult BlogCover(int id)
        {
            var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);
        }

        [AllowAnonymous]
        public PartialViewResult BlogReadAll(int id)
        {
            var BlogDetailsList = bm.GetBlogByID(id);
            return PartialView(BlogDetailsList);
        }

        [AllowAnonymous]
        public ActionResult BlogByCategory(int id)
        {
            var BlogListByCategory = bm.GetBlogByCategory(id);
            var CategoryName = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryName).FirstOrDefault();
            ViewBag.CategoryName = CategoryName;
            var CategoryDescription = bm.GetBlogByCategory(id).Select(y => y.Category.CategoryDescription).FirstOrDefault();
            ViewBag.CategoryDescription = CategoryDescription;
            return View(BlogListByCategory);
        }

        public ActionResult AdminBlogList()
        {
            var bloglist = bm.GetList();
            return View(bloglist);
        }

        public ActionResult AdminBlogList2()
        {
            var bloglist = bm.GetList();
            return View(bloglist);
        }

        [Authorize(Roles ="A")]
        [HttpGet]
        public ActionResult AddNewBlog()
        {
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                          select new SelectListItem
                                          {
                                              Text = x.CategoryName,
                                              Value = x.CategoryID.ToString()
                                          }).ToList();
            ViewBag.values = values;

            List<SelectListItem> values2 = (from x in c.Authors.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.AuthorName,
                                               Value = x.AuthorID.ToString()
                                           }).ToList();
            ViewBag.values2 = values2;
            return View();
        }

        [HttpPost]
        public ActionResult AddNewBlog(Blog b)
        {
            bm.TAdd(b);
            return RedirectToAction("AdminBlogList");
        }
        
        public ActionResult DeleteBlog(int id)
        {
            Blog blog = bm.GetByID(id);
            bm.TDelete(blog);
            return RedirectToAction("AdminBlogList");
        }

        [HttpGet]
        public ActionResult UpdateBlog(int id)
        {
            Blog blog = bm.GetByID(id);
            Context c = new Context();
            List<SelectListItem> values = (from x in c.Categories.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CategoryName,
                                               Value = x.CategoryID.ToString()
                                           }).ToList();
            ViewBag.values = values;

            List<SelectListItem> values2 = (from x in c.Authors.ToList()
                                            select new SelectListItem
                                            {
                                                Text = x.AuthorName,
                                                Value = x.AuthorID.ToString()
                                            }).ToList();
            ViewBag.values2 = values2;
            return View(blog);
        }

        [HttpPost]
        public ActionResult UpdateBlog(Blog p)
        {
            bm.TUpdate(p);
            return RedirectToAction("AdminBlogList");
        }


        public ActionResult GetCommentByBlog(int id)
        {
            var commentlist = cm.CommentByBlog(id);
            return View(commentlist);
        }

        public ActionResult AuthorBlogList(int id)
        {
            var blogs = bm.GetBlogByAuthor(id);
            return View(blogs);
        }


    }
}

mvc_blog_projesi/Controllers/CommentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc_blog_projesi.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment

        CommentManager cm = new CommentManager(new EfCommentDal());
        [AllowAnonymous]
        public PartialViewResult CommentList(int id)
        {
            var commentlist = cm.CommentByBlog(id);

            return PartialView(commentlist);
        }

        [AllowAnonymous]
        [HttpGet]
        public PartialViewResult LeaveComment(int id)
        {
            ViewBag.id = id;
            return PartialView();
        }

        [AllowAnonymous]
        [HttpPost]
        public PartialViewResult LeaveComment(Comment c)
        {
            c.CommentStatus = true;
            cm.TAdd(c);
            return PartialView();
        }

        public ActionResult AdminCommentListTrue()
        {
            var commentlist=cm.CommentByStatusTrue();
            return View(commentlist);
        }

        public ActionResult StatusChangeToFalse(int id)
        {
            cm.CommentStatusChangeToFalse(id);
            return RedirectToAction("AdminCommentListTrue");
        }

        public ActionResult AdminCommentListFalse()
        {
            var commentlist = cm.CommentByStatusFalse();
            return View(commentlist);
        }

        public ActionResult StatusChangeToTrue(int id)
        {
            cm.CommentStatusChangeToTrue(id);
            return RedirectToAction("AdminCommentListFalse");
        }

    }
}

mvc_blog_projesi/Controllers/MailSubscribeController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvc_blog_projesi.Controllers
{
    [AllowAnonymous]

    public class MailSubscribeController : Controller
    {
        SubscribeMailManager sm = new SubscribeMailManager(new EfMailDal());

        // GET: MailSubscribe

        [HttpGet]
        public PartialViewResult AddMail()
        {
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult AddMail(SubscribeMail p)
        {
            sm.TAdd(p);
            return PartialView();
        }
    }
}

mvc_blog_projesi/Views/Blog/AddNewBlog.cshtml
@model EntityLayer.Concrete.Blog

@{
    ViewBag.Title = "AddNewBlog";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<form class="form-group" method="post">
    @Html.Label("Başlık")
    @Html.TextBoxFor(x => x.BlogName, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.values, new { @class = "form-control" })
    <br />
    @Html.Label("Resim Linki")
    @Html.TextBoxFor(x => x.BlogImage, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.BlogDate, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.AuthorID, (List<SelectListItem>)ViewBag.values2, new { @class = "form-control" })
    <br />
    @Html.Label("Metin")
    @Html.TextAreaFor(x => x.BlogContent, 5, 20, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Kaydet</button>
</form>

mvc_blog_projesi/Views/Blog/AdminBlogList.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@{
    ViewBag.Title = "AdminBlogList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Blog Listesi</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Başlık</th>
        <th>Kategori</th>
        <th>Tarih</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
        <th>Yorumlar</th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.BlogID</td>
                    <td>@item.BlogName</td>
                    <td>@item.Category.CategoryName</td>
                    <td>@item.BlogDate.ToShortDateString()</td>
                    <td><a href="/Blog/DeleteBlog/@item.BlogID" class="btn btn-danger">Sil</a></td>
                    <td><a href="/Blog/UpdateBlog/@item.BlogID" class="btn btn-warning">Güncelle</a></td>
                    <td><a href="/Blog/BlogDetails/@item.BlogID" target="_blank" class="btn btn-info">Detaylar</a></td>
                    <td><a href="/Blog/GetCommentByBlog/@item.BlogID" target="_blank" class="btn btn-secondary">Yorumlar</a></td>
                </tr>
            }
</table>

<a href="/Blog/AddNewBlog/" class="btn btn-primary">Yeni Yazı Ekle</a>

mvc_blog_projesi/Views/Blog/AdminBlogList2.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>

@{
    ViewBag.Title = "AdminBlogList2";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Blog Listesi</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                ID
                            </th>
                            <th style="width: 20%">
                                Blog Başlığı
                            </th>
                            <th style="width: 6%">
                                Yazar
                            </th>
                            <th style="width: 10%">
                                Beğeni Durumu
                            </th>
                            <th style="width: 4%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 10%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.BlogID</td>
                                <td>@item.BlogName</td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Author.AuthorImage">
                                        </li>
                                    </ul>
                                </td>
                                <td class="project_progress">
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-green" role="progressbar" aria-volumenow="57" aria-volumemin="0" aria-volumemax="100" style="width: 57%">
                                        </div>
                                    </div>
                                    <small>
                                        57% Complete
                                    </small>
                                </td>
                                <td class="project-state">
                                    <span @*class="badge badge-success"*@>@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Blog/BlogDetails/@item.BlogID">
                                        <i class="fas fa-folder">
                                        </i>
                                        Sitede Gör
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Blog/UpdateBlog/@item.BlogID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Blog/DeleteBlog/@item.BlogID">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </section>
</body>
</html>

mvc_blog_projesi/Views/Blog/AuthorBlogList.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>

@{
    ViewBag.Title = "AuthorBlogList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{string color = "";}
@{string casename = "";}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Blog Listesi</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                ID
                            </th>
                            <th style="width: 20%">
                                Blog Adı
                            </th>
                            <th style="width: 20%">
                                Kategori Adı
                            </th>
                            <th>
                                Blog Puanı
                            </th>
                            <th style="width: 10%" class="text-center">
                                Blog Durumu
                            </th>
                            <th style="width: 15%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.BlogRating >= 85)
                            {
                                color = "post-category text-white bg-success mb-3";
                                casename = "Mükemmel";
                            }
                            if (item.BlogRating >= 70 && item.BlogRating <= 84)
                            {
                                color = "post-category text-white bg-primary mb-3";
                                casename = "Başarılı";
                            }
                            if (item.BlogRating >= 50 && item.BlogRating <= 69)
                            {
                                color = "post-category text-white bg-warning mb-3";
                                casename = "Fena Değil";
                            }
                            if (item.BlogRating <= 49)
                            {
                                color = "post-category text-white bg-danger mb-3";
                                casename = "Gelişime açık";
                            }

                            <tr>
                                <td>@item.BlogID</td>
                                <td>@item.BlogName</td>
                                <td>@item.Category.CategoryName</td>
                                <td class="project_progress">
                                    <div class="progress progress-sm">
                                        <div class="progress-bar bg-green" role="progressbar" aria-volumenow="@item.BlogRating" aria-volumemin="0" aria-volumemax="10" style="width: @item.BlogRating%">
                                        </div>
                                    </div>
                                    <small>
                                        Blog Puanı: @item.BlogRating
                                    </small>
                                </td>
                                <td class="project-state">
                                    <span class="badge @color">@casename</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-info btn-sm" href="/Blog/UpdateBlog/@item.BlogID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="#">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <a href="/Blog/AddNewBlog/" class="btn btn-primary">Yeni Blog Ekle</a>
        <!-- /.card -->
    </section>
</body>
</html>

mvc_blog_projesi/Views/Blog/BlogByCategory.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>

@{
    ViewBag.Title = "BlogByCaegory";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="py-5 bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <span>Kategori</span>
                
                <h3>@ViewBag.CategoryName</h3>
                <p>@ViewBag.CategoryDescription</p>
                
            </div>
        </div>
    </div>
</div>

<div class="site-section bg-white">
   <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
            <div class="col-lg-4 mb-4">
                <div class="entry2">
                    <a href="/Blog/BlogDetails/@item.BlogID"><img src="@item.BlogImage" alt="Image" style="height:250px" class="img-fluid rounded"></a>
                    <div class="excerpt">
                        <span class="post-category text-white bg-secondary mb-3">@item.Category.CategoryName</span>

                        <h2><a href="/Blog/BlogDetails/@item.BlogID">@item.BlogName</a></h2>
                        <div class="post-meta align-items-center text-left clearfix">
                            <figure class="author-figure mb-0 mr-3 float-left"><img src="@item.Author.AuthorImage" alt="Image" class="img-fluid"></figure>
                            <span class="d-inline-block mt-1">By <a href="#">@item.Author.AuthorName</a></span>
                            <span>&nbsp;-&nbsp; @(((DateTime)item.BlogDate).ToString("dd-MMM-yyyy"))</span>
                        </div>

                        <p>@item.BlogContent.Substring(0, item.BlogContent.Substring(0, 200).LastIndexOf(" "))...</p>
                        <p><a href="#">Read More</a></p>
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
</div>

@Html.Action("Footer","About")

mvc_blog_projesi/Views/Blog/BlogDetails.cshtml
@{
    ViewBag.Title = "BlogDetails";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("BlogCover", "Blog")

<section class="site-section py-lg">
    <div class="container">

        <div class="row blog-entries element-animate">

            <div class="col-md-12 col-lg-8 main-content">
                @Html.Action("BlogReadAll", "Blog")
                @Html.Action("CommentList", "Comment")
            </div>
            <div class="col-md-12 col-lg-4 sidebar">
                @Html.Action("AuthorAbout", "Author")
                @Html.Action("AuthorPopularPost", "Author")
                @Html.Action("BlogDetailsCategoryList", "Category")

            </div>
        </div>
    </div>
</section>

@Html.Action("OtherFeaturedPost", "Blog")

@Html.Action("AddMail", "MailSubscribe")

@Html.Action("Footer", "About")

mvc_blog_projesi/Views/Blog/BlogReadAll.cshtml
@model IEnumerable<EntityLayer.Concrete.Blog>
@foreach (var item in Model)
{
    <div class="post-content-body">
        <p>@item.BlogContent</p>
            <div class="row mb-5 mt-5">
            <div class="col-md-12 mb-4">
                <img src="@item.BlogImage" alt="Image placeholder" class="img-fluid rounded">
            </div>
        </div>
     </div>
}

mvc_blog_projesi/Views/Blog/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@Html.Action("FeaturedPost", "Blog")

@Html.Action("BlogList", "Blog")

@Html.Action("AddMail", "MailSubscribe")

@Html.Action("Footer", "About")